export const REMOVE_COMMENT_REQUESTED = 'UNIVERSITY/FEED/RemoveComment/REMOVE_COMMENT_REQUESTED';
export const REMOVE_COMMENT_SUCCEED = 'UNIVERSITY/FEED/RemoveComment/REMOVE_COMMENT_SUCCEED';
export const REMOVE_COMMENT_FAILED = 'UNIVERSITY/FEED/RemoveComment/REMOVE_COMMENT_FAILED';
export const REMOVE_COMMENT_RESET = 'UNIVERSITY/FEED/RemoveComment/REMOVE_COMMENT_RESET';
