export const SEND_COM_EMOJI_REQUESTED = 'UNIVERSITY/FEED/SendComEmoji/SEND_COM_EMOJI_REQUESTED';
export const SEND_COM_EMOJI_SUCCEED = 'UNIVERSITY/FEED/SendComEmoji/SEND_COM_EMOJI_SUCCEED';
export const SEND_COM_EMOJI_FAILED = 'UNIVERSITY/FEED/SendComEmoji/SEND_COM_EMOJI_FAILED';
export const SEND_COM_EMOJI_RESET = 'UNIVERSITY/FEED/SendComEmoji/SEND_COM_EMOJI_RESET';
