export const RESET_PASSWORD_REQUESTED = 'AUTHENTICATION/RESET_PASSWORD_REQUESTED';
export const RESET_PASSWORD_SUCCEED = 'AUTHENTICATION/RESET_PASSWORD_SUCCEED';
export const RESET_PASSWORD_FAILED = 'AUTHENTICATION/RESET_PASSWORD_FAILED';
