export const GET_LECTURES_REQUESTED = 'LECTURES/GET_LECTURES_REQUESTED';
export const GET_LECTURES_SUCCEED = 'LECTURES/GET_LECTURES_SUCCEED';
export const GET_LECTURES_FAILED = 'LECTURES/GET_LECTURES_FAILED';
export const GET_LECTURES_RESET = 'LECTURES/GET_LECTURES_RESET';
