export const GET_COMMENTS_REQUESTED = 'COMMENTS/GET_COMMENTS_REQUESTED';
export const GET_COMMENTS_SUCCEED = 'COMMENTS/GET_COMMENTS_SUCCEED';
export const GET_COMMENTS_FAILED = 'COMMENTS/GET_COMMENTS_FAILED';
export const GET_COMMENTS_RESET = 'COMMENTS/GET_COMMENTS_RESET';
