export const GET_UNI_INFO_REQUESTED = 'UNIVERSITY/GET_UNI_INFO_REQUESTED';
export const GET_UNI_INFO_SUCCEED = 'UNIVERSITY/GET_UNI_INFO_SUCCEED';
export const GET_UNI_INFO_FAILED = 'UNIVERSITY/GET_UNI_INFO_FAILED';
export const GET_UNI_INFO_RESET = 'UNIVERSITY/GET_UNI_INFO_RESET';
