export const POST_NEW_FEED_REQUESTED = 'UNIVERSITY/POST_NEW_FEED_REQUESTED';
export const POST_NEW_FEED_SUCCEED = 'UNIVERSITY/POST_NEW_FEED_SUCCEED';
export const POST_NEW_FEED_FAILED = 'UNIVERSITY/POST_NEW_FEED_FAILED';
