export const GET_FACULTIES_REQUESTED = 'UNIVERSITY/GET_FACULTIES_REQUESTED';
export const GET_FACULTIES_SUCCEED = 'UNIVERSITY/GET_FACULTIES_SUCCEED';
export const GET_FACULTIES_FAILED = 'UNIVERSITY/GET_FACULTIES_FAILED';
export const GET_FACULTIES_RESET = 'UNIVERSITY/GET_FACULTIES_RESET';
