export const GET_POST_REACTIONS_REQUESTED = 'UNIVERSITY/FEED/GetPostReactions/GET_POST_REACTIONS_REQUESTED';
export const GET_POST_REACTIONS_SUCCEED = 'UNIVERSITY/FEED/GetPostReactions/GET_POST_REACTIONS_SUCCEED';
export const GET_POST_REACTIONS_FAILED = 'UNIVERSITY/FEED/GetPostReactions/GET_POST_REACTIONS_FAILED';
export const GET_POST_REACTIONS_RESET = 'UNIVERSITY/FEED/GetPostReactions/GET_POST_REACTIONS_RESET';
