export const UPDATE_UNI_RATE_REQUESTED = 'UNIVERSITY/UPDATE_UNI_RATE_REQUESTED';
export const UPDATE_UNI_RATE_SUCCEED = 'UNIVERSITY/UPDATE_UNI_RATE_SUCCEED';
export const UPDATE_UNI_RATE_FAILED = 'UNIVERSITY/UPDATE_UNI_RATE_FAILED';
export const UPDATE_UNI_RATE_RESET = 'UNIVERSITY/UPDATE_UNI_RATE_RESET';
