export const NEW_USER_REGISTER_REQUESTED = 'AUTHENTICATION/NEW_USER_REGISTER_REQUESTED';
export const NEW_USER_REGISTER_SUCCEED = 'AUTHENTICATION/NEW_USER_REGISTER_SUCCEED';
export const NEW_USER_REGISTER_FAILED = 'AUTHENTICATION/NEW_USER_REGISTER_FAILED';
