export const UPDATE_RATE_REQUESTED = 'LECTURES/UPDATE_RATE_REQUESTED';
export const UPDATE_RATE_SUCCEED = 'LECTURES/UPDATE_RATE_SUCCEED';
export const UPDATE_RATE_FAILED = 'LECTURES/UPDATE_RATE_FAILED';
export const UPDATE_RATE_RESET = 'LECTURES/UPDATE_RATE_RESET';
