export const GET_GRANTS_DETAILS_REQUESTED = 'UNIVERSITY/GET_GRANTS_DETAILS_REQUESTED';
export const GET_GRANTS_DETAILS_SUCCEED = 'UNIVERSITY/GET_GRANTS_DETAILS_SUCCEED';
export const GET_GRANTS_DETAILS_FAILED = 'UNIVERSITY/GET_GRANTS_DETAILS_FAILED';
export const GET_GRANTS_DETAILS_RESET = 'UNIVERSITY/GET_GRANTS_DETAILS_RESET';
