export const GET_POSTS_REQUESTED = 'UNIVERSITY/FEED/GET_POSTS_REQUESTED';
export const GET_POSTS_SUCCEED = 'UNIVERSITY/FEED/GET_POSTS_SUCCEED';
export const GET_POSTS_FAILED = 'UNIVERSITY/FEED/GET_POSTS_FAILED';
export const GET_POSTS_RESET = 'UNIVERSITY/FEED/GET_POSTS_RESET';
