export const UPDATE_USER_INFO_REQUESTED = 'User/UpdateUserInfo/UPDATE_USER_INFO_REQUESTED';
export const UPDATE_USER_INFO_SUCCEED = 'User/UpdateUserInfo/UPDATE_USER_INFO_SUCCEED';
export const UPDATE_USER_INFO_FAILED = 'User/UpdateUserInfo/UPDATE_USER_INFO_FAILED';
export const UPDATE_USER_INFO_RESET = 'User/UpdateUserInfo/UPDATE_USER_INFO_RESET';
