export const UPDATE_POST_REQUESTED = 'UNIVERSITY/FEED/UpdatePost/UPDATE_POST_REQUESTED';
export const UPDATE_POST_SUCCEED = 'UNIVERSITY/FEED/UpdatePost/UPDATE_POST_SUCCEED';
export const UPDATE_POST_FAILED = 'UNIVERSITY/FEED/UpdatePost/UPDATE_POST_FAILED';
export const UPDATE_POST_RESET = 'UNIVERSITY/FEED/UpdatePost/UPDATE_POST_RESET';
