export const UPDATE_FETCHED_POSTS_LIST = 'UNIVERSITY/FEED/FetchedPosts/UPDATE_FETCHED_POSTS_LIST';
export const ADD_POST = 'UNIVERSITY/FEED/FetchedPosts/ADD_POST';
export const REMOVE_POST = 'UNIVERSITY/FEED/FetchedPosts/REMOVE_POST';
export const UPDATE_POST = 'UNIVERSITY/FEED/FetchedPosts/UPDATE_POST';
export const SET_COMMENTS_POST = 'UNIVERSITY/FEED/FetchedPosts/SET_COMMENTS_POST';
export const RESET_COMMENTS_POST = 'UNIVERSITY/FEED/FetchedPosts/RESET_COMMENTS_POST';
