export const UPDATE_COMMENT_REQUESTED = 'LECTURES/UPDATE_COMMENT_REQUESTED';
export const UPDATE_COMMENT_SUCCEED = 'LECTURES/UPDATE_COMMENT_SUCCEED';
export const UPDATE_COMMENT_FAILED = 'LECTURES/UPDATE_COMMENT_FAILED';
export const UPDATE_COMMENT_RESET = 'LECTURES/UPDATE_COMMENT_RESET';
