export const UPDATE_COMMENT_REQUESTED = 'UNIVERSITY/FEED/UpdateComment/UPDATE_COMMENT_REQUESTED';
export const UPDATE_COMMENT_SUCCEED = 'UNIVERSITY/FEED/UpdateComment/UPDATE_COMMENT_SUCCEED';
export const UPDATE_COMMENT_FAILED = 'UNIVERSITY/FEED/UpdateComment/UPDATE_COMMENT_FAILED';
export const UPDATE_COMMENT_RESET = 'UNIVERSITY/FEED/UpdateComment/UPDATE_COMMENT_RESET';
