export const FILTER_LECTURERS_REQUESTED = 'LECTURERS/FILTER_LECTURERS_REQUESTED';
export const FILTER_LECTURERS_SUCCEED = 'LECTURERS/FILTER_LECTURERS_SUCCEED';
export const FILTER_LECTURERS_FAILED = 'LECTURERS/FILTER_LECTURERS_FAILED';
export const FILTER_LECTURERS_RESET = 'LECTURERS/FILTER_LECTURERS_RESET';
