export const ADD_COMMENT_REQUESTED = 'UNIVERSITY/FEED/AddComment/ADD_COMMENT_REQUESTED';
export const ADD_COMMENT_SUCCEED = 'UNIVERSITY/FEED/AddComment/ADD_COMMENT_SUCCEED';
export const ADD_COMMENT_FAILED = 'UNIVERSITY/FEED/AddComment/ADD_COMMENT_FAILED';
export const ADD_COMMENT_RESET = 'UNIVERSITY/FEED/AddComment/ADD_COMMENT_RESET';
