export const NEW_USER_REGISTER_REQUESTED = 'NEW_USER_REGISTER_REQUESTED';
export const NEW_USER_REGISTER_SUCCEED = 'NEW_USER_REGISTER_SUCCEED';
export const NEW_USER_REGISTER_FAILED = 'NEW_USER_REGISTER_FAILED';
