export const LOGIN_REQUESTED = 'AUTHENTICATION/LOGIN_REQUESTED';
export const LOGIN_SUCCEED = 'AUTHENTICATION/LOGIN_SUCCEED';
export const LOGIN_FAILED = 'AUTHENTICATION/LOGIN_FAILED';
export const LOGIN_RESET = 'AUTHENTICATION/LOGIN_RESET';
