export const REMOVE_COMMENT_REQUESTED = 'LECTURES/REMOVE_COMMENT_REQUESTED';
export const REMOVE_COMMENT_SUCCEED = 'LECTURES/REMOVE_COMMENT_SUCCEED';
export const REMOVE_COMMENT_FAILED = 'LECTURES/REMOVE_COMMENT_FAILED';
export const REMOVE_COMMENT_RESET = 'LECTURES/REMOVE_COMMENT_RESET';
