export const ADD_COMMENT_REQUESTED = 'LECTURES/ADD_COMMENT_REQUESTED';
export const ADD_COMMENT_SUCCEED = 'LECTURES/ADD_COMMENT_SUCCEED';
export const ADD_COMMENT_FAILED = 'LECTURES/ADD_COMMENT_FAILED';
export const ADD_COMMENT_RESET = 'LECTURES/ADD_COMMENT_RESET';
