export const CHECK_TOKEN_REQUESTED = 'AUTHENTICATION/CHECK_TOKEN_REQUESTED';
export const CHECK_TOKEN_SUCCEED = 'AUTHENTICATION/CHECK_TOKEN_SUCCEED';
export const CHECK_TOKEN_FAILED = 'AUTHENTICATION/CHECK_TOKEN_FAILED';
