export const GET_COMMENTS_REQUESTED = 'UNIVERSITY/FEED/GetComments/GET_COMMENTS_REQUESTED';
export const GET_COMMENTS_SUCCEED = 'UNIVERSITY/FEED/GetComments/GET_COMMENTS_SUCCEED';
export const GET_COMMENTS_FAILED = 'UNIVERSITY/FEED/GetComments/GET_COMMENTS_FAILED';
export const GET_COMMENTS_RESET = 'UNIVERSITY/FEED/GetComments/GET_COMMENTS_RESET';
