export const ADD_NEW_POST_REQUESTED = 'UNIVERSITY/FEED/ADD_NEW_POST_REQUESTED';
export const ADD_NEW_POST_SUCCEED = 'UNIVERSITY/FEED/ADD_NEW_POST_SUCCEED';
export const ADD_NEW_POST_FAILED = 'UNIVERSITY/FEED/ADD_NEW_POST_FAILED';
export const ADD_NEW_POST_RESET = 'UNIVERSITY/FEED/ADD_NEW_POST_RESET';
