export const CHANGE_PASSWORD_REQUESTED = 'User/ChangePassword/CHANGE_PASSWORD_REQUESTED';
export const CHANGE_PASSWORD_SUCCEED = 'User/ChangePassword/CHANGE_PASSWORD_SUCCEED';
export const CHANGE_PASSWORD_FAILED = 'User/ChangePassword/CHANGE_PASSWORD_FAILED';
export const CHANGE_PASSWORD_RESET = 'User/ChangePassword/CHANGE_PASSWORD_RESET';
