export const ACTIVATION_REQUESTED = 'AUTHENTICATION/ACTIVATION_REQUESTED';
export const ACTIVATION_SUCCEED = 'AUTHENTICATION/ACTIVATION_SUCCEED';
export const ACTIVATION_FAILED = 'AUTHENTICATION/ACTIVATION_FAILED';
