export const SEND_POST_EMOJI_REQUESTED = 'UNIVERSITY/FEED/SendPostEmoji/SEND_POST_EMOJI_REQUESTED';
export const SEND_POST_EMOJI_SUCCEED = 'UNIVERSITY/FEED/SendPostEmoji/SEND_POST_EMOJI_SUCCEED';
export const SEND_POST_EMOJI_FAILED = 'UNIVERSITY/FEED/SendPostEmoji/SEND_POST_EMOJI_FAILED';
export const SEND_POST_EMOJI_RESET = 'UNIVERSITY/FEED/SendPostEmoji/SEND_POST_EMOJI_RESET';
