export const REMOVE_POST_REQUESTED = 'UNIVERSITY/FEED/RemovePost/REMOVE_POST_REQUESTED';
export const REMOVE_POST_SUCCEED = 'UNIVERSITY/FEED/RemovePost/REMOVE_POST_SUCCEED';
export const REMOVE_POST_FAILED = 'UNIVERSITY/FEED/RemovePost/REMOVE_POST_FAILED';
export const REMOVE_POST_RESET = 'UNIVERSITY/FEED/RemovePost/REMOVE_POST_RESET';
