export const GET_FILTERED_UNI_LIST_REQUESTED = 'UNIVERSITY/GET_FILTERED_UNI_LIST_REQUESTED';
export const GET_FILTERED_UNI_LIST_SUCCEED = 'UNIVERSITY/GET_FILTERED_UNI_LIST_SUCCEED';
export const GET_FILTERED_UNI_LIST_FAILED = 'UNIVERSITY/GET_FILTERED_UNI_LIST_FAILED';
export const GET_FILTERED_UNI_LIST_RESET = 'UNIVERSITY/GET_FILTERED_UNI_LIST_RESET';
