export const FORGOT_PASSWORD_REQUESTED = 'AUTHENTICATION/FORGOT_PASSWORD_REQUESTED';
export const FORGOT_PASSWORD_SUCCEED = 'AUTHENTICATION/FORGOT_PASSWORD_SUCCEED';
export const FORGOT_PASSWORD_FAILED = 'AUTHENTICATION/FORGOT_PASSWORD_FAILED';
